[project]
name = "kerberos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "claude-code-sdk>=0.0.23",
    "rich>=14.1.0",
    "textual",
    "textual-terminal @ git+https://github.com/mitosch/textual-terminal.git@refs/pull/13/head",
]
